version: 3

env:
  # git init したディレクトリ
  PROJECT_ROOT: /home/isucon/webapp

dotenv:
  - .env.example

includes:
  app: ./taskfiles/app.yml
  bench: ./taskfiles/bench.yml
  db: ./taskfiles/db.yml
  discord: ./taskfiles/discord.yml
  git: ./taskfiles/git.yml
  nginx: ./taskfiles/nginx.yml
  util: ./taskfiles/util.yml

tasks:
  default:
    desc: neko
    cmds:
      - echo Nyan
